on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: "16.x" # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install, build
        run: |
          npm install
          npm run build:prod

      - name: Upload to storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: $web
          connection_string: ${{ secrets.CONNECTION_STRING }}
          overwrite: "true"
